language:
    - python

python:
    - "3.3"

env:
    # 01
    - EXAMPLE=01-executable TOOLCHAIN=default CONFIG=Debug
    - EXAMPLE=01-executable TOOLCHAIN=default CONFIG=Release
    - EXAMPLE=01-executable TOOLCHAIN=clang-libstdcxx CONFIG=Debug
    - EXAMPLE=01-executable TOOLCHAIN=clang-libstdcxx CONFIG=Release
    - EXAMPLE=01-executable TOOLCHAIN=gcc-4-8 CONFIG=Debug
    - EXAMPLE=01-executable TOOLCHAIN=gcc-4-8 CONFIG=Release
    - EXAMPLE=01-executable TOOLCHAIN=analyze CONFIG=Debug
    - EXAMPLE=01-executable TOOLCHAIN=analyze CONFIG=Release
    - EXAMPLE=01-executable TOOLCHAIN=sanitize-address CONFIG=Debug
    - EXAMPLE=01-executable TOOLCHAIN=sanitize-address CONFIG=Release
    - EXAMPLE=01-executable TOOLCHAIN=sanitize-leak CONFIG=Debug
    - EXAMPLE=01-executable TOOLCHAIN=sanitize-leak CONFIG=Release
    - EXAMPLE=01-executable TOOLCHAIN=sanitize-thread CONFIG=Debug
    - EXAMPLE=01-executable TOOLCHAIN=sanitize-thread CONFIG=Release
    # 02
    - EXAMPLE=02-library TOOLCHAIN=default CONFIG=Debug
    - EXAMPLE=02-library TOOLCHAIN=default CONFIG=Release
    - EXAMPLE=02-library TOOLCHAIN=clang-libstdcxx CONFIG=Debug
    - EXAMPLE=02-library TOOLCHAIN=clang-libstdcxx CONFIG=Release
    - EXAMPLE=02-library TOOLCHAIN=gcc-4-8 CONFIG=Debug
    - EXAMPLE=02-library TOOLCHAIN=gcc-4-8 CONFIG=Release
    - EXAMPLE=02-library TOOLCHAIN=analyze CONFIG=Debug
    - EXAMPLE=02-library TOOLCHAIN=analyze CONFIG=Release
    - EXAMPLE=02-library TOOLCHAIN=sanitize-address CONFIG=Debug
    - EXAMPLE=02-library TOOLCHAIN=sanitize-address CONFIG=Release
    - EXAMPLE=02-library TOOLCHAIN=sanitize-leak CONFIG=Debug
    - EXAMPLE=02-library TOOLCHAIN=sanitize-leak CONFIG=Release
    - EXAMPLE=02-library TOOLCHAIN=sanitize-thread CONFIG=Debug
    - EXAMPLE=02-library TOOLCHAIN=sanitize-thread CONFIG=Release
    # 03
    - EXAMPLE=03-shared-link TOOLCHAIN=default CONFIG=Debug
    - EXAMPLE=03-shared-link TOOLCHAIN=default CONFIG=Release
    - EXAMPLE=03-shared-link TOOLCHAIN=clang-libstdcxx CONFIG=Debug
    - EXAMPLE=03-shared-link TOOLCHAIN=clang-libstdcxx CONFIG=Release
    - EXAMPLE=03-shared-link TOOLCHAIN=gcc-4-8 CONFIG=Debug
    - EXAMPLE=03-shared-link TOOLCHAIN=gcc-4-8 CONFIG=Release
    - EXAMPLE=03-shared-link TOOLCHAIN=analyze CONFIG=Debug
    - EXAMPLE=03-shared-link TOOLCHAIN=analyze CONFIG=Release
    - EXAMPLE=03-shared-link TOOLCHAIN=sanitize-address CONFIG=Debug
    - EXAMPLE=03-shared-link TOOLCHAIN=sanitize-address CONFIG=Release
    - EXAMPLE=03-shared-link TOOLCHAIN=sanitize-leak CONFIG=Debug
    - EXAMPLE=03-shared-link TOOLCHAIN=sanitize-leak CONFIG=Release
    - EXAMPLE=03-shared-link TOOLCHAIN=sanitize-thread CONFIG=Debug
    - EXAMPLE=03-shared-link TOOLCHAIN=sanitize-thread CONFIG=Release

install:
    # install gcc 4.8 and libstdc++
    #   * github.com/travis-ci-tester/travis-test-gcc-cxx-11
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
    - sudo apt-get update
    - sudo apt-get install g++-4.8
    # -- end
    - sudo apt-get install cmake
    - sudo apt-get install libcurl3-dev
    # install cmake
    - CMAKE_VERSION="3.0.2-ios-universal"
    - wget "https://github.com/ruslo/CMake/archive/v${CMAKE_VERSION}.tar.gz"
    - openssl sha1 "v${CMAKE_VERSION}.tar.gz"
    - tar xf "v${CMAKE_VERSION}.tar.gz"
    - cd "CMake-${CMAKE_VERSION}"
    -   cmake -H. -B_builds -DCMAKE_INSTALL_PREFIX="`pwd`/_install/" -DCMAKE_BUILD_TYPE=Release -DCMAKE_USE_SYSTEM_CURL=YES
    -   cmake --build _builds --target install
    -   export PATH="`pwd`/_install/bin:${PATH}"
    - cd ..
    # -- end

script:
    - export POLLY_ROOT="`pwd`"
    - which cmake
    - python3 ./examples/jenkins.py
