language:
    - cpp

env:
    # default gcc version don't support c++11
    - EXAMPLE=00-simple TOOLCHAIN=clang32_libstdcxx
    - EXAMPLE=01-executable TOOLCHAIN=default
    - EXAMPLE=01-executable TOOLCHAIN=gcc48
    - EXAMPLE=01-executable TOOLCHAIN=clang32_libstdcxx
    - EXAMPLE=02-library TOOLCHAIN=default
    - EXAMPLE=02-library TOOLCHAIN=gcc48
    - EXAMPLE=02-library TOOLCHAIN=clang32_libstdcxx

before_install:
    - export POLLY_ROOT=`pwd`

install:
    # install clang 3.2 and gcc 4.8
    #   * github.com/travis-ci-tester/travis-test-clang-3.2
    #   * github.com/travis-ci-tester/travis-test-gcc-cxx-11
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
    - sudo add-apt-repository --yes ppa:h-rayflood/llvm
    - sudo apt-get update
    - sudo apt-get install g++-4.8
    - sudo apt-get install clang-3.2
    # -- end
    # install cmake 2.8.8
    #     * github.com/travis-ci-tester/travis-test-cmake
    - "wget https://launchpad.net/ubuntu/+source/cmake/2.8.8-2ubuntu1/+build/3441442/+files/cmake_2.8.8-2ubuntu1_amd64.deb"
    - "wget https://launchpad.net/ubuntu/+archive/primary/+files/cmake-data_2.8.8-2ubuntu1_all.deb"
    - "sudo apt-get remove cmake-data cmake"
    - "sudo dpkg --install cmake-data_2.8.8-2ubuntu1_all.deb cmake_2.8.8-2ubuntu1_amd64.deb"
    # -- end
    # download sugar for 02-library example
    - wget https://github.com/ruslo/sugar/archive/v1.0.0.tar.gz
    - tar xf *.tar.gz
    - export SUGAR_ROOT=`pwd`/sugar-1.0.0
    # -- end

script:
    - cd ${POLLY_ROOT}/examples/${EXAMPLE}
    # release
    - mkdir -p _builds/make-release
    - cd _builds/make-release
    - cmake -DCMAKE_TOOLCHAIN_FILE=${POLLY_ROOT}/${TOOLCHAIN}.cmake -DCMAKE_BUILD_TYPE=Release ../..
    - cmake --build .
    - ctest -V .
    - cmake --build . --target install
    - cd ../..
    # debug
    - mkdir -p _builds/make-debug
    - cd _builds/make-debug
    - cmake -DCMAKE_TOOLCHAIN_FILE=${POLLY_ROOT}/${TOOLCHAIN}.cmake -DCMAKE_BUILD_TYPE=Debug ../..
    - cmake --build .
    - ctest -V .
    - cmake --build . --target install
    - cd ../..
